### PR TITLE
Use actual conditions to designate paths, instead of opcodes with args

### PR DESCRIPTION
**Pull request by dgpv**
For easier comprehension of the report, and also to improve accuracy of the display of the conditions, I decided to change the way the conditions in the paths are displayed

Instead of

```
IF wit0 @ 0:L1 : True
---------------------
```

It will now be

```
When wit0 = 1 :: [IF @ 0:L1]
----------------------------
```

for modes when `MINIMALDATA` is enabled,

and

```
When BOOL(wit0) is True :: [IF @ 0:L1]
--------------------------------------
```

for the modes when `MINIMALDATA` is disabled.

For `IFDUP`,

instead of

```
IFDUP wit0 @ 0:L1 : True
------------------------
```

it will be

```
When BOOL(wit0) is True :: [IFDUP @ 0:L1]
-----------------------------------------
```

When the path is created by `NOTIF`, the actual condition will be shown, thus `notif 1 else 2 endif` with `MINIMALDATA` enabled, will result in

```
============
Valid paths:
============

When wit0 = 0 :: [NOTIF @ 0:L1]
-------------------------------

When wit0 = 1 :: [NOTIF @ 0:L1]
-------------------------------

==============================
Enforced constraints per path:
==============================

When wit0 = 0 :: [NOTIF @ 0:L1]
-------------------------------

        1 @ END

When wit0 = 1 :: [NOTIF @ 0:L1]
-------------------------------

        BOOL(2) @ END
```

For `PICK` and `ROLL`, instead of

```
PICK wit0 @ 0:L1 : 3, ...
-------------------------
```

it will be

```
When wit0 = 3, ... :: [PICK @ 0:L1]
-----------------------------------
```

For elements opcodes that create branches, it will be like this:

```
When DIV64(wit1, wit0) is valid :: [DIV64 @ 0:L1]
-------------------------------------------------
```

```
When MUL64(wit0, wit1) is invalid :: [MUL64 @ 0:L1]
---------------------------------------------------
```

```
When INPUT(wit0) has no issuance :: [INSPECTINPUTISSUANCE @ 0:L1]
-----------------------------------------------------------------
```

For multiple conditions, instead of

```
IF wit0 @ 0:L1 : True
NOTIF wit1 @ 1:L1 : False
IFDUP wit2 @ 2:L1 : True
-------------------------
```

They will be connected with `And`:

```
When wit0 = 1 :: [IF @ 0:L1]
 And wit1 = 0 :: [NOTIF @ 1:L1]
 And BOOL(wit2) :: [IFDUP @ 2:L1]
---------------------------------
```

In my opinion, this will make the report easier to comprehend, as the reader will see the actual conditions, and will not have to do transformations in their head, like for `NOTIF`. Script-bool vs 1/0 distinction will also be shown where it was not shown before

I did not merge it right away in case someone have an idea how this can be done better, or can give a reason why changing it in this way might not be a good idea

Please give your opinions on this change.

### CODE REVIEW

**Comment by ajtowns** [comment]
How does this work with multiple conditions on the same witness? eg:

```
IF GREATERTHANOREQUAL(wit0, 32) @ 27:L16 : True
IF GREATERTHANOREQUAL(SUB(wit0, 32), 16) @ 38:L17 : True
IF GREATERTHANOREQUAL(SUB(SUB(wit0, 32), 16), 8) @ 49:L18 : False
```

would be nice to read as:

```
When 48 <= wit0 < 56: [IF @ 27:L16, IF @ 38:L17, not-IF @ 49:L18]
```

It might also be nice if constant conditions were elided; eg I'm seeing:

```
        LESSTHAN(128, 256) @ 137:L36
```

reported as the only constraint for some branches, which seems a bit noisy.

I'm also seeing:

```
All valid paths:
        EQUAL(1, SIZE(wit1)) @ 60:L22
...
IF EQUAL(wit1, x('80')) @ 66:L24 : False
IF LESSTHAN(wit1, 0) @ 73:L25 : False
IF EQUAL(0, SUB(SUB(SUB(wit0, 32), 16), 8)) @ 81:L28 : False
IF EQUAL(1, SUB(SUB(SUB(wit0, 32), 16), 8)) @ 88:L29 : True
------------------------------------------------------------

        LESSTHAN(wit1, 128) @ 137:L36
```

which could in theory be removed: all values expressible with size 1 are less than 128, and the only one that would cause a failure is 0x80 (non-minimal zero), which has been explicitly excluded.

**Comment by dgpv** [comment]
Can you share the script that creates these conditions in the report ? I could craft one, but if it already exists, I won't need to spend time on that

**Comment by dgpv** [comment]
> It might also be nice if constant conditions were elided; eg I'm seeing:
> LESSTHAN(128, 256) @ 137:L36
> reported as the only constraint for some branches, which seems a bit noisy.

Hmm, this seems to be an always-true condition, and it should be possible to safely remove that condition, because it does not affect the results

I think hiding these conditions will do a disservice, because you can miss a bug where the condition was not actually intended to be always-true

I wonder if there cases where you just cannot write the script in a better way to get rid of such obviously always-true conditions

It would be nice to look at examples

**Comment by dgpv** [comment]
`When 48 <= wit0 < 56: [IF @ 27:L16, IF @ 38:L17, not-IF @ 49:L18]`

I think doing this automatically will be too complex, it will require different engine than simple Z3 SMT/SAT solver

Right now B'SST does not actually "know" anything about arithmetic in the general sense. Just each opcode executed/traced adds their constraints.

Maybe this can be done with adding information manually via annotations. Like, create a special assert and check that the automatically-built branch condition is equivalent to this assert condition, or equivalent to its inverse.

This will work for the cases where you can find an opcode that is only present in this branch, otherwise there will be a need to somehow relate these manually-annotated branch conditions to the automatically-built branch conditions.

**Comment by dgpv** [comment]
> which could in theory be removed: all values expressible with size 1 are less than 128, and the only one that would cause a failure is 0x80 (non-minimal zero), which has been explicitly excluded.

Maybe I did not understand, but if you analyze with `--z3-enabled=true`, the report will show that the enforcement condition is 'always true'

For example, this script: `dup size 1 equalverify 0x80 equal not if 128 lessthan verify endif`, when analyzed with `--z3-enabled=true --is-incomplete-script=true --mark-path-local-always-true-enforcements=false` will show

```
All valid paths:
----------------

        EQUAL(1, SIZE(wit0)) @ 3:L1

When NOT(EQUAL(wit0, x('80'))) = 1 :: [IF @ 7:L1]
-------------------------------------------------

        <*> LESSTHAN(wit0, 128) @ 10:L1

```
where `<*>` indicates that the condition is always true

**Comment by dgpv** [comment]
I am thinking about using branch condition to show data references.

For example, now it is like this:

```
 ./bsst-cli
0 lessthan if 5 else 10 endif // =>x
add

...

Enforced constraints per path:
==============================

When LESSTHAN(wit0, 0) = 1 :: [IF @ 2:L1]
-----------------------------------------

        BOOL(ADD(&x, wit1)) @ END

When LESSTHAN(wit0, 0) = 0 :: [IF @ 2:L1]
-----------------------------------------

        BOOL(ADD(&x', wit1)) @ END

...

================
Data references:
================

        x = 5
        x' = 10
```

But it can be made into

```
...

BOOL(ADD(&x, wit1)) @ END

...

================
Data references:
================

When LESSTHAN(wit0, 0) = 1 :: [IF @ 2:L1]
-----------------------------------------
        x = 5

When LESSTHAN(wit0, 0) = 0 :: [IF @ 2:L1]
-----------------------------------------
        x = 10
```

Or even

```
        x = Case
           When LESSTHAN(wit0, 0) = 1
              And LESSTHAN(wit1, 0) = 1

           => SUB(wit2, 5)

           When LESSTHAN(wit0, 0) = 1
              And LESSTHAN(wit1, 0) = 0

           => ADD(wit2, 1)

           When LESSTHAN(wit0, 0) = 0
              And LESSTHAN(wit1, 0) = 1
           Or
           When LESSTHAN(wit0, 0) = 0
              And LESSTHAN(wit1, 0) = 0
           => wit2
```

I don't think it will be a good idea to use 'default case' here, like `Else` or `Otherwise` etc., Maybe only for the case when there is only two possible values for the reference, and there is no invalid branches. Because if some branches always fail, using 'defult' case can end up masking this information. Of course the failed cases will be shown later in the report, but I think this 'masking' can still lead to confusion

The last two conditions that is joined by `Or` can be simplified, because the full range of `LESSTHAN(wit1, 0)` is included in both cases. Simplifying this would require to track possible ranges of the conditions, which is not tracked now. Branches can have non-binary conditions, like for `PICK` or other opcodes that can take variable number of arguments.

**Comment by ajtowns** [comment]
> Can you share the script that creates these conditions in the report ? I could craft one, but if it already exists, I won't need to spend time on that

I was trying to debug it first :) The idea is it's a choose-your-own proof-of-work script, so you pass in a desired difficulty and a preimage, and the difficulty controls both a CSV delay, and how many 0-bits the hash of your preimage needs to contain.

```
DUP 0 GREATERTHANOREQUAL VERIFY
DUP 64 LESSTHAN VERIFY

DUP
// multiply by 10:
DUP ADD DUP DUP ADD DUP ADD ADD
640 SWAP SUB
CHECKSEQUENCEVERIFY DROP


FALSE TOALTSTACK
DUP 32 GREATERTHANOREQUAL IF FROMALTSTACK 0x00000000 CAT TOALTSTACK 32 SUB ENDIF
DUP 16 GREATERTHANOREQUAL IF FROMALTSTACK 0x0000 CAT TOALTSTACK 16 SUB ENDIF
DUP  8 GREATERTHANOREQUAL IF FROMALTSTACK 0x00 CAT TOALTSTACK  8 SUB ENDIF


SWAP
SIZE 1 EQUALVERIFY
DUP TOALTSTACK
1 CAT 256 SUB
SWAP

DUP 0 EQUAL IF DROP 256 ELSE
DUP 1 EQUAL IF DROP 128 ELSE
DUP 2 EQUAL IF DROP  64 ELSE
DUP 3 EQUAL IF DROP  32 ELSE
DUP 4 EQUAL IF DROP  16 ELSE
DUP 5 EQUAL IF DROP   8 ELSE
DUP 6 EQUAL IF DROP   4 ELSE
               DROP   2
ENDIF ENDIF ENDIF ENDIF ENDIF ENDIF ENDIF LESSTHAN VERIFY

FROMALTSTACK FROMALTSTACK CAT CAT TOALTSTACK

// sig pubkey prefix suffix
2OVER
SIZE 32 EQUALVERIFY DROP
SIZE 64 EQUALVERIFY
SWAP CAT CAT HASH256 FROMALTSTACK EQUALVERIFY

CHECKSIG
```

witneses are: `difficulty hash_first_nonzero hash_rest preimage_suffix preimage_prefix pubkey signature`.

I found the easiest way to check its behaviour was to special case on wit0:

```sh
$ for a in `seq 0 64`; do echo $a $(date -R); (echo "DUP $a EQUALVERIFY"; cat varpow) | ./bsst-cli --is-elements=true > varpow.result-$a; done
$ for a in `seq 1 63`; do echo $a; cat varpow.result-$a | grep -E '^  *(LESSTHAN.*wit1|EQUAL.*HASH256)' | sort -u; echo; done | less
```

**Comment by ajtowns** [comment]
> Maybe I did not understand, but if you analyze with `--z3-enabled=true`, the report will show that the enforcement condition is 'always true'

z3 isn't working for me; I'm getting:

```
Exception ignored in: <function AstRef.__del__ at 0x7f076dd445e0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 351, in __del__
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 724, in as_ast
TypeError: 'NoneType' object is not callable
Exception ignored in: <function AstRef.__del__ at 0x7f076dd445e0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 351, in __del__
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 724, in as_ast
TypeError: 'NoneType' object is not callable
```

python3-z3 4.8.12-3.1+b2 from Debian, commit 942f7bca3a360e22cf07b54818e0dfae80f33aae from bsst.

**Comment by ajtowns** [comment]
> Hmm, this seems to be an always-true condition, and it should be possible to safely remove that condition, because it does not affect the results
> 
> I think hiding these conditions will do a disservice, because you can miss a bug where the condition was not actually intended to be always-true

I think there's maybe two different cases
 * where you're trying to get an overview of what the script does, in which case you want to report just the cases where the condition is spendable, and what the constraints are
 * where you're trying to understand in depth how the script works, either because it doesn't do what you want and you're debugging it, or just for a better understanding in general, in which case you want to be able to explore all the paths in detail

I'm doing the first case, so hiding the impossible things would be good for me right now, but the second case is definitely a real thing too.

**Comment by dgpv** [comment]
> z3 isn't working for me

I've created an issue for this. It looks like something related to particular package versions, it will require time to investigate.

I've ran `bsst-cli --is-elements=true --z3-enabled=true` on the script you have provided above, and I'm attaching the report here, in case the info on 'always-true' conditions and model values can be useful to you

[pow.script.report.txt](https://github.com/dgpv/bsst/files/15394804/pow.script.report.txt)

**Comment by dgpv** [comment]
Interesting that the report in the previous message shows

```
==============================
Enforced constraints per path:
==============================

All valid paths:
----------------

        {*} GREATERTHANOREQUAL(wit0, 0) @ 3:L1
        {*} LESSTHAN(wit0, 64) @ 7:L2
```

while I would not expect to see `{*}` in the section for "all valid paths", because if it is always true for all valid paths, it should be marked with `<*>`. Will need to look into it

**Comment by dgpv** [comment]
> I'm doing the first case, so hiding the impossible things would be good for me right now, but the second case is definitely a real thing too.

I would say that 'always-true' enforcements are not "impossible" things. If you do not care about the facts that script might be doing something irrelevant, like checking a condition that is always true, then ignoring them does not do harm.

But for bsst to find out that the enforcement is always true, it will need Z3 enabled. And then it will mark that enforcement with `<*>` or `{*}`

I guess there could be a mode that will eliminate always-true enforcements from the report. But I think it will need to come with a visible warning indicating that the information reported about the script is not complete

**Comment by ajtowns** [comment]
> > I'm doing the first case, so hiding the impossible things would be good for me right now, but the second case is definitely a real thing too.
> 
> I would say that 'always-true' enforcements are not "impossible" things. They might be called "irrelevant" in some narrow context.

If I do `(echo 'DUP 12 EQUALVERIFY'; cat varpow) | ./bsst-cli --explicitly-enabled-opcodes=CAT | less` then I see:

```
==============================
Enforced constraints per path:
==============================

All valid paths:
----------------

        EQUAL(12, wit0) @ 2:L1
        GREATERTHANOREQUAL(wit0, 0) @ 6:L3
        LESSTHAN(wit0, 64) @ 10:L4
        CSV(SUB(640, ADD(ADD(ADD(ADD(wit0, wit0), ADD(wit0, wit0)), ADD(ADD(wit0, wit0), ADD(wit0, wit0))), ADD(wit0, wit0)))) @ 23:L12
        EQUAL(1, SIZE(wit1)) @ 63:L22
        LESSTHAN(SUB(wit1.1, 256), 16) @ 123:L35
        EQUAL(32, SIZE(wit5)) @ 132:L41
        EQUAL(64, SIZE(wit6)) @ 136:L42
        EQUAL(wit2.wit1.x('').x('00'), HASH256(wit4.wit6.wit3)) @ 142:L43
        CHECKSIG(wit6, wit5) @ END

IF GREATERTHANOREQUAL(wit0, 32) @ 30:L16 : False
------------------------------------------------

        EQUAL(12, wit0) @ 2:L1
        GREATERTHANOREQUAL(wit0, 0) @ 6:L3
        LESSTHAN(wit0, 64) @ 10:L4
        CSV(SUB(640, ADD(ADD(ADD(ADD(wit0, wit0), ADD(wit0, wit0)), ADD(ADD(wit0, wit0), ADD(wit0, wit0))), ADD(wit0, wit0)))) @ 23:L12
        EQUAL(1, SIZE(wit1)) @ 63:L22
        LESSTHAN(SUB(wit1.1, 256), 16) @ 123:L35
        EQUAL(32, SIZE(wit5)) @ 132:L41
        EQUAL(64, SIZE(wit6)) @ 136:L42
        EQUAL(wit2.wit1.x('').x('00'), HASH256(wit4.wit6.wit3)) @ 142:L43
        CHECKSIG(wit6, wit5) @ END
```

but that's just telling me the same thing twice, which is confusing -- there's only that one valid path, so everything is all-valid-paths.

I then also see a whole lot of `Failures per path:` which seems redundant, since they're just different violations of the constraints from the valid paths.

> If you do not care about the facts that script might be doing something irrelevant, like checking a condition that is always true, then ignoring them doe not do harm.

Well, bsst isn't really for performance analysis? Like, if I say `DUP DROP DUP DROP 2DUP 2DROP DUP DROP`, it's not meant to tell me I'm being daft, right?

I think there's an aliasing-ish bug too:

```
DUP 99 GREATERTHAN IF 1000 ADD ENDIF
50 LESSTHAN IF 10 ELSE 20 ENDIF
CHECKSEQUENCEVERIFY
```

has the constraints are reported as:

```
IF LESSTHAN(ADD(1000, wit0), 50) @ 9:L3 : True
----------------------------------------------

        CSV(10) @ 14:L3
        BOOL(10) @ END

IF LESSTHAN(ADD(1000, wit0), 50) @ 9:L3 : False
-----------------------------------------------

        CSV(20) @ 14:L3
        BOOL(20) @ END
```

but it's only `ADD(1000, wit0)` conditionally, at other times it's just `wit0`. Assigning a reference and indicating the reference value is conditional on paths would probably be ideal?

**Comment by dgpv** [comment]
> but it's only ADD(1000, wit0) conditionally, at other times it's just wit0. Assigning a reference and indicating the reference value is conditional on paths would probably be ideal?

I think this is what I described at the end of this post: https://github.com/dgpv/bsst/issues/36, with the `x = Case ...` construction

Or do you have something other in mind ?

**Comment by dgpv** [comment]
> > If you do not care about the facts that script might be doing something irrelevant, like checking a condition that is always true, then ignoring them doe not do harm.
>
> Well, bsst isn't really for performance analysis? Like, if I say `DUP DROP DUP DROP 2DUP 2DROP DUP DROP`, it's not meant to tell me I'm being daft, right?

This is about comparing of what you expect the script to do, and what it actually does. Usually you would not expect the script to do something useless, and so it can indicate a bug

Seeing an unexpected always-true condition has helped me uncover a critical bug in at least one script that I thought was final and good to go

**Comment by dgpv** [comment]
I think it would be great to detect 'effect-less' code fragments like  `DUP DROP DUP DROP 2DUP 2DROP DUP DROP`, because it also can help detect the bugs, just like the compiler warnings can tell you that you probably want to look at this piece of code second time.

Right now bsst can only detect always-true enforcement conditions, but not effect-less code. I can be a useful enhancement.

It should be possible to 'turn off the warnings', though. But because the focus of bsst from the beginning was helping to detect the bugs, turning off warnings should result in one big warning at the start of the report, that tells that warnings are off :-)

**Comment by ajtowns** [comment]
> I think this is what I described at the end of this post: #36, with the `x = Case ...` construction

:+1:

Really, I think this probably solves the "trivially true" case for me too: the condition would become `LESSTHAN(&ref, 10)` in general, and `ref=5` in a particular case, instead of `LESSTHAN(5, 10)` in the particular case.

**Comment by dgpv** [comment]
I am thinking that instead of

```
When GREATERTHANOREQUAL(wit0, 32) = 1 :: [IF @ 27:L12]

...

When GREATERTHANOREQUAL(wit0, 32) = 0 :: [IF @ 27:L12]

```

it should be

```
When GREATERTHANOREQUAL(wit0, 32) :: [IF @ 27:L12]

...

When Not GREATERTHANOREQUAL(wit0, 32) :: [IF @ 27:L12]

```

Will need some additional code, but will be much more readable

**Comment by dgpv** [comment]
> > Hmm, this seems to be an always-true condition, and it should be possible to safely remove that condition, because it does not affect the results
> > I think hiding these conditions will do a disservice, because you can miss a bug where the condition was not actually intended to be always-true
> 
> I think there's maybe two different cases
> 
>     * where you're trying to get an overview of what the script does, in which case you want to report just the cases where the condition is spendable, and what the constraints are
> 
>     * where you're trying to understand in depth how the script works, either because it doesn't do what you want and you're debugging it, or just for a better understanding in general, in which case you want to be able to explore all the paths in detail
> 
> 
> I'm doing the first case, so hiding the impossible things would be good for me right now, but the second case is definitely a real thing too.

Added `--hide-always-true-enforcements` setting in https://github.com/dgpv/bsst/commit/c3cb8e0811705459bbed8e2dd5f1021f589e0bf3

**Pull request merged**
